version: "3.9"

services:
  app:
    build: .
    container_name: campus-marketplace-app
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      PORT: 3000

      # 🔥 REPLACE THIS WITH YOUR REAL NEON URL
      DATABASE_URL: "postgresql://neondb_owner:npg_6HGZfAMylg1Q@ep-broad-sea-aiac91g8-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=verify-full&channel_binding=require"


      JWT_SECRET: change-me
      JWT_EXPIRES_IN: 7d
      ADMIN_USERNAMES: admin

      CLOUDINARY_CLOUD_NAME: ""
      CLOUDINARY_API_KEY: ""
      CLOUDINARY_API_SECRET: ""

      BOT_TOKEN: ""

    # Optional: wait a bit before starting (helps DB readiness)
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm start
      "